# Generated by Django 2.0.8 on 2018-08-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'pagina',
                'verbose_name_plural': 'paginas',
                'ordering': ['-title'],
            },
        ),
    ]
